# Generated by Django 5.1.6 on 2025-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customeraddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
